name: First Workflow
on: 
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - master
      - 'dev-*'
      - 'dev/**'
    paths-ignore:
      - '.github/workflows/*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Output envent data
        run: echo "${{ toJSON(github.event) }}"
      - name: checkout
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependency
        run: npm ci
